version: 2

project_name: awstbx

builds:
  - id: awstbx
    main: ./cmd/awstbx
    binary: awstbx
    goos:
      - linux
      - darwin
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w
      - -X github.com/towardsthecloud/aws-toolbox/internal/version.Version={{.Version}}
      - -X github.com/towardsthecloud/aws-toolbox/internal/version.Commit={{.ShortCommit}}
      - -X github.com/towardsthecloud/aws-toolbox/internal/version.Date={{.Date}}

archives:
  - id: awstbx
    formats: [tar.gz]
    name_template: "awstbx_{{ .Version }}_{{ .Os }}_{{ .Arch }}"

checksum:
  name_template: checksums.txt

homebrew_casks:
  - repository:
      owner: towardsthecloud
      name: homebrew-tap
      token: "{{ .Env.HOMEBREW_TAP_GITHUB_TOKEN }}"
    directory: Casks
    homepage: https://github.com/towardsthecloud/aws-toolbox
    description: Unified CLI for AWS infrastructure automation
    license: MIT
    binaries:
      - awstbx

changelog:
  disable: true
