package main

import (
	"flag"
	"fmt"
	"os"
	"strconv"
	"strings"
	"time"

	"github.com/spf13/cobra"
	"github.com/spf13/cobra/doc"
	"github.com/towardsthecloud/aws-toolbox/internal/cli"
)

func main() {
	markdownDir := flag.String("markdown-dir", "docs/cli", "directory for generated markdown command reference")
	manDir := flag.String("man-dir", "docs/man", "directory for generated man pages")
	flag.Parse()

	rootCmd := cli.NewRootCommand()
	disableAutoGenTags(rootCmd)

	if err := os.MkdirAll(*markdownDir, 0o755); err != nil {
		fatalf("create markdown directory: %v", err)
	}
	if err := os.MkdirAll(*manDir, 0o755); err != nil {
		fatalf("create man directory: %v", err)
	}

	filePrepender := func(string) string {
		return "> Generated by `go run ./cmd/awstbx-docs`.\n\n"
	}

	if err := doc.GenMarkdownTreeCustom(rootCmd, *markdownDir, filePrepender, func(s string) string { return s }); err != nil {
		fatalf("generate markdown docs: %v", err)
	}

	manDate, err := resolveManHeaderDate()
	if err != nil {
		fatalf("resolve man page header date: %v", err)
	}

	header := &doc.GenManHeader{
		Title:   "AWSTBX",
		Section: "1",
		Source:  "awstbx",
		Manual:  "AWS Toolbox CLI",
		Date:    &manDate,
	}
	if err := doc.GenManTree(rootCmd, header, *manDir); err != nil {
		fatalf("generate man pages: %v", err)
	}
}

func resolveManHeaderDate() (time.Time, error) {
	epochText := strings.TrimSpace(os.Getenv("SOURCE_DATE_EPOCH"))
	if epochText == "" {
		return time.Unix(0, 0).UTC(), nil
	}

	epoch, err := strconv.ParseInt(epochText, 10, 64)
	if err != nil {
		return time.Time{}, fmt.Errorf("invalid SOURCE_DATE_EPOCH %q: %w", epochText, err)
	}

	return time.Unix(epoch, 0).UTC(), nil
}

func disableAutoGenTags(cmd *cobra.Command) {
	cmd.DisableAutoGenTag = true
	for _, child := range cmd.Commands() {
		disableAutoGenTags(child)
	}
}

func fatalf(format string, args ...any) {
	_, _ = fmt.Fprintf(os.Stderr, format+"\n", args...)
	os.Exit(1)
}
